#!/usr/bin/env python3
"""
Auto-layout script for preamp-zener PCB boards.
Reads netlists generated by `pcb layout`, imports footprints from KiCad libraries,
places components, adds board outlines and copper pours, then saves.
"""

import os
import re
import pcbnew
from pathlib import Path

BOARDS_DIR = Path(__file__).parent / "boards"
KICAD_FP_DIR = Path("/usr/share/kicad/footprints")
CACHE_FP_DIR = Path(__file__).parent / ".pcb/cache/gitlab.com/kicad/libraries/kicad-footprints/9.0.3"

# Map footprint library names from netlist to actual .pretty directories
FPLIB_MAP = {
    "MountingHole_2.2mm_M2_DIN965_Pad_TopBottom": ("MountingHole.pretty", "MountingHole_2.2mm_M2_DIN965_Pad_TopBottom"),
    "MountingHole_2.2mm_M2_Pad": ("MountingHole.pretty", "MountingHole_2.2mm_M2_Pad"),
    "PinHeader_1x08_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_1x08_P2.54mm_Vertical"),
    "PinSocket_1x08_P2.54mm_Vertical": ("Connector_PinSocket_2.54mm.pretty", "PinSocket_1x08_P2.54mm_Vertical"),
    "PinHeader_1x02_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_1x02_P2.54mm_Vertical"),
    "PinHeader_2x05_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_2x05_P2.54mm_Vertical"),
    "PinHeader_2x06_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_2x06_P2.54mm_Vertical"),
    "PinHeader_1x20_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_1x20_P2.54mm_Vertical"),
    "PinSocket_1x20_P2.54mm_Vertical": ("Connector_PinSocket_2.54mm.pretty", "PinSocket_1x20_P2.54mm_Vertical"),
}


def find_footprint_lib(fpid_str):
    """Find the .pretty directory and footprint name for a given FPID string.
    Handles both 'lib:footprint' and plain 'footprint' formats."""
    if ":" in fpid_str:
        lib_name, fp_name = fpid_str.split(":", 1)
    else:
        lib_name = fpid_str
        fp_name = fpid_str

    # Check our explicit map — prioritize system KiCad 7 libs over cache (KiCad 9 format)
    if fp_name in FPLIB_MAP:
        pretty_dir, actual_fp = FPLIB_MAP[fp_name]
        for base in [KICAD_FP_DIR, CACHE_FP_DIR]:
            lib_path = base / pretty_dir
            if lib_path.exists() and (lib_path / f"{actual_fp}.kicad_mod").exists():
                return str(lib_path), actual_fp

    # Try to find by searching .pretty directories — system first
    for base in [KICAD_FP_DIR, CACHE_FP_DIR]:
        if not base.exists():
            continue
        for pretty in base.iterdir():
            if pretty.suffix == ".pretty":
                fp_file = pretty / f"{fp_name}.kicad_mod"
                if fp_file.exists():
                    return str(pretty), fp_name

    return None, None


def parse_netlist(net_path):
    """Parse KiCad netlist (.net) file to extract components and nets."""
    with open(net_path, 'r') as f:
        content = f.read()

    components = []
    # Extract component entries
    comp_pattern = re.compile(
        r'\(comp \(ref "([^"]+)"\)\s*'
        r'\(value "([^"]+)"\)\s*'
        r'\(footprint "([^"]+)"\)',
        re.DOTALL
    )
    for m in comp_pattern.finditer(content):
        ref, value, footprint = m.groups()
        components.append({
            'ref': ref,
            'value': value,
            'footprint': footprint,
        })

    # Extract nets — use paren-balanced extraction for multi-node nets
    nets = []
    node_pattern = re.compile(r'\(node \(ref "([^"]+)"\) \(pin "([^"]+)"\)')
    # Find each (net ...) block by balancing parentheses
    net_start = re.compile(r'\(net \(code "\d+"\) \(name "([^"]+)"\)')
    for m in net_start.finditer(content):
        net_name = m.group(1)
        # Find balanced closing paren from start of (net ...)
        start_pos = m.start()
        depth = 0
        end_pos = start_pos
        for i in range(start_pos, len(content)):
            if content[i] == '(':
                depth += 1
            elif content[i] == ')':
                depth -= 1
                if depth == 0:
                    end_pos = i + 1
                    break
        net_block = content[start_pos:end_pos]
        nodes = [(n.group(1), n.group(2)) for n in node_pattern.finditer(net_block)]
        nets.append({'name': net_name, 'nodes': nodes})

    return components, nets


def create_board(board_name, components, nets, board_config):
    """Create a KiCad PCB with placed components."""
    board = pcbnew.BOARD()

    # Set title
    title_block = board.GetTitleBlock()
    title_block.SetTitle(board_name)

    # Set design rules
    ds = board.GetDesignSettings()
    ds.SetCopperLayerCount(board_config.get('layers', 2))
    ds.m_TrackMinWidth = pcbnew.FromMM(0.2)
    ds.m_ViasMinSize = pcbnew.FromMM(0.6)
    ds.m_ViasMinDrill = pcbnew.FromMM(0.3)
    ds.m_CopperEdgeClearance = pcbnew.FromMM(0.25)

    # Set default track width and clearance
    ds.m_MinClearance = pcbnew.FromMM(0.2)

    # Load and place footprints
    placed_fps = {}
    for comp in components:
        ref = comp['ref']
        fpid = comp['footprint']

        lib_path, fp_name = find_footprint_lib(fpid)
        if lib_path is None:
            print(f"  WARNING: Could not find footprint for {ref}: {fpid}")
            continue

        try:
            fp = pcbnew.FootprintLoad(lib_path, fp_name)
        except Exception as e:
            print(f"  WARNING: Failed to load {fp_name} from {lib_path}: {e}")
            continue

        fp.SetReference(ref)
        fp.SetValue(comp['value'])
        board.Add(fp)
        placed_fps[ref] = fp

    # Create nets and assign to pads
    netinfo = board.GetNetInfo()
    for net_entry in nets:
        net_name = net_entry['name']
        net_item = pcbnew.NETINFO_ITEM(board, net_name)
        board.Add(net_item)

    # Refresh net info after adding all nets
    netinfo = board.GetNetInfo()
    nets_by_name = netinfo.NetsByName()

    for net_entry in nets:
        net_name = net_entry['name']
        if not nets_by_name.has_key(net_name):
            continue
        net_obj = nets_by_name[net_name]
        for ref, pin in net_entry['nodes']:
            if ref in placed_fps:
                fp = placed_fps[ref]
                for pad in fp.Pads():
                    if pad.GetNumber() == pin:
                        pad.SetNet(net_obj)
                        break

    return board, placed_fps


def mm_pos(x, y):
    """Create a VECTOR2I position from mm coordinates."""
    return pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y))


def place_components_grid(board, placed_fps, layout_spec):
    """Place components according to layout specification."""
    for ref, (x, y, rot) in layout_spec.items():
        if ref in placed_fps:
            fp = placed_fps[ref]
            fp.SetPosition(mm_pos(x, y))
            fp.SetOrientationDegrees(rot)


def add_board_outline(board, x, y, w, h, corner_radius=0):
    """Add rectangular board outline on Edge.Cuts layer."""
    edge_layer = board.GetLayerID("Edge.Cuts")

    # Simple rectangle outline (corner_radius ignored for API compatibility)
    for (x1, y1, x2, y2) in [
        (x, y, x + w, y),
        (x + w, y, x + w, y + h),
        (x + w, y + h, x, y + h),
        (x, y + h, x, y),
    ]:
        line = pcbnew.PCB_SHAPE(board)
        line.SetShape(pcbnew.SHAPE_T_SEGMENT)
        line.SetStart(mm_pos(x1, y1))
        line.SetEnd(mm_pos(x2, y2))
        line.SetLayer(edge_layer)
        line.SetWidth(pcbnew.FromMM(0.1))
        board.Add(line)


def add_ground_pour(board, net_name, layer_name, x, y, w, h):
    """Add a copper pour (zone) for ground or power plane."""
    netinfo = board.GetNetInfo()
    nets_by_name = netinfo.NetsByName()
    if not nets_by_name.has_key(net_name):
        print(f"  WARNING: Net '{net_name}' not found for copper pour")
        return

    net = nets_by_name[net_name]
    layer_id = board.GetLayerID(layer_name)

    zone = pcbnew.ZONE(board)
    zone.SetNet(net)
    zone.SetLayer(layer_id)
    zone.SetIsRuleArea(False)
    zone.SetDoNotAllowTracks(False)
    zone.SetDoNotAllowVias(False)
    zone.SetDoNotAllowPads(False)
    zone.SetDoNotAllowCopperPour(False)

    # Create outline
    outline = zone.Outline()
    outline.NewOutline()
    outline.Append(pcbnew.FromMM(x), pcbnew.FromMM(y))
    outline.Append(pcbnew.FromMM(x + w), pcbnew.FromMM(y))
    outline.Append(pcbnew.FromMM(x + w), pcbnew.FromMM(y + h))
    outline.Append(pcbnew.FromMM(x), pcbnew.FromMM(y + h))

    # Set zone properties
    zone.SetMinThickness(pcbnew.FromMM(0.25))
    zone.SetThermalReliefGap(pcbnew.FromMM(0.5))
    zone.SetThermalReliefSpokeWidth(pcbnew.FromMM(0.5))

    board.Add(zone)


# ============================================================
# Net-based passive clustering helpers
# ============================================================

def build_net_map(nets):
    """Build ref -> set(net_names) and net_name -> set(refs) maps."""
    ref_to_nets = {}
    net_to_refs = {}
    for net_entry in nets:
        net_name = net_entry['name']
        for ref, pin in net_entry['nodes']:
            ref_to_nets.setdefault(ref, set()).add(net_name)
            net_to_refs.setdefault(net_name, set()).add(ref)
    return ref_to_nets, net_to_refs


POWER_NETS = {'AGND', 'DGND', 'AVDD', 'DVDD', 'VBUS', 'VBAT', 'VBAT_RAW'}


def assign_passives_to_anchors(fps, nets, anchor_positions):
    """Assign each passive to nearest anchor it shares signal nets with."""
    ref_to_nets, net_to_refs = build_net_map(nets)
    anchor_refs = set(anchor_positions.keys())
    assignments = {}  # anchor_ref -> [passive_refs]
    _power_rr_counters = {}  # round-robin counters for power domain distribution

    for ref in fps:
        if ref in anchor_refs or ref.startswith(('H', 'RV')):
            continue
        if not ref.startswith(('R', 'C')):
            continue

        my_nets = ref_to_nets.get(ref, set())
        my_signal_nets = my_nets - POWER_NETS

        # Find anchor sharing the most signal nets
        best_anchor = None
        best_score = 0
        for net_name in my_signal_nets:
            for other_ref in net_to_refs.get(net_name, set()):
                if other_ref in anchor_refs and other_ref != ref:
                    score = len(my_signal_nets & ref_to_nets.get(other_ref, set()))
                    if score > best_score:
                        best_score = score
                        best_anchor = other_ref

        # Fallback: find anchor via shared power nets (for decoupling caps)
        if best_anchor is None:
            # Try to find via transitive signal connections (passive shares net with another
            # passive that connects to an anchor)
            for net_name in my_signal_nets:
                for mid_ref in net_to_refs.get(net_name, set()):
                    if mid_ref != ref and mid_ref.startswith(('R', 'C')):
                        mid_signal = ref_to_nets.get(mid_ref, set()) - POWER_NETS
                        for mn in mid_signal:
                            for ar in net_to_refs.get(mn, set()):
                                if ar in anchor_refs:
                                    best_anchor = ar
                                    break
                            if best_anchor:
                                break
                    if best_anchor:
                        break
                if best_anchor:
                    break

        # Last resort: distribute power-only caps round-robin across ICs in domain
        if best_anchor is None:
            my_power = my_nets & POWER_NETS
            if 'AVDD' in my_power or 'AGND' in my_power:
                analog_ics = [c for c in ['U1', 'U2', 'U5', 'U9', 'U10', 'U7', 'U8', 'U3']
                              if c in anchor_refs]
                if analog_ics:
                    idx = _power_rr_counters.get('analog', 0) % len(analog_ics)
                    best_anchor = analog_ics[idx]
                    _power_rr_counters['analog'] = idx + 1
            elif 'DVDD' in my_power or 'DGND' in my_power:
                digital_ics = [c for c in ['U6', 'U4', 'U1', 'U2', 'U5']
                               if c in anchor_refs]
                if digital_ics:
                    idx = _power_rr_counters.get('digital', 0) % len(digital_ics)
                    best_anchor = digital_ics[idx]
                    _power_rr_counters['digital'] = idx + 1

        if best_anchor is None:
            best_anchor = 'UNASSIGNED'
        assignments.setdefault(best_anchor, []).append(ref)

    return assignments


def place_passives_near_anchor(anchor_x, anchor_y, passive_refs, layout, x_dir=1):
    """Place passive components clustered around an anchor position."""
    n = len(passive_refs)
    # Adaptive columns: more passives = wider spread
    cols = min(5, max(2, n // 2))
    spacing_x = 4.5 * x_dir
    spacing_y = 3.5
    start_x = anchor_x + 6 * x_dir
    start_y = anchor_y - min(3, (n // cols) * 1.5)
    for i, ref in enumerate(sorted(passive_refs)):
        col = i % cols
        row = i // cols
        x = start_x + col * spacing_x
        y = start_y + row * spacing_y
        layout[ref] = (x, y, 0)


# ============================================================
# Board-specific layout configurations
# ============================================================

def layout_main():
    """Layout the unified MAIN board (master + ADC + DAC-router + slaves)."""
    board_dir = BOARDS_DIR / "main" / "layout"
    net_path = board_dir / "default.net"

    if not net_path.exists():
        print("  MAIN netlist not found, skipping")
        return

    print("  Parsing netlist...")
    components, nets = parse_netlist(net_path)
    print(f"  Found {len(components)} components, {len(nets)} nets")

    board, fps = create_board("main", components, nets, {'layers': 4})

    # Board dimensions: 200x100mm, 4-layer, three zones
    bw, bh = 200, 100
    ox, oy = 10, 10  # board origin

    layout = {}

    # =================================================================
    # Explicit IC and connector placement by reference designator
    # =================================================================
    #
    # Ref mapping (from netlist analysis):
    #   J19 = USB-C          J4 = Battery connector
    #   U4 = MCP73831        U3 = LP2985 (AVDD)     U6 = AP2114H (DVDD)
    #   D1 = BAT54           D2 = LED (charge status)
    #   J1 = Master left socket (1x20)   J2 = Master right socket (1x20)
    #   J8/J15 = Slave A     J9/J16 = Slave B
    #   J10/J17 = Slave C    J11/J18 = Slave D
    #   U1 = ES8388 #1       U2 = ES8388 #2
    #   J3 = J_AFE (2x5 preamp cable)
    #   U5 = HT8988A DAC     U9 = NE5532 summing    U10 = NE5532 output buf
    #   U7 = CD4052B mux #1  U8 = CD4052B mux #2
    #   J7 = HP jack         J12 = Line jack
    #   RV1/RV2 = Volume pots
    #   J13/J14 = Output headers   J5/J6 = Footswitch connectors
    #   FB1 = Ferrite bead (AGND-DGND bridge)

    # ================================================================
    # ZONE A — DIGITAL (left ~95mm, x: ox to ox+90)
    # ================================================================

    # --- Power supply section (top-left corner) ---
    layout['J19'] = (ox + 8,  oy + 6, 270)      # USB-C on left edge, rotated
    layout['U4']  = (ox + 24, oy + 6, 0)        # MCP73831 charger near USB-C
    layout['D1']  = (ox + 38, oy + 6, 0)        # BAT54 reverse protection
    layout['D2']  = (ox + 20, oy + 3, 0)        # Charge status LED
    layout['J4']  = (ox + 8,  oy + 22, 0)       # Battery connector on left edge

    layout['U3']  = (ox + 28, oy + 20, 0)       # LP2985 analog LDO
    layout['U6']  = (ox + 55, oy + 8, 0)        # AP2114H digital LDO (SOT-223, wider gap from U4)

    # Ferrite bead at analog/digital zone boundary
    layout['FB1'] = (ox + 92, oy + 40, 0)

    # --- Master ESP32 DevKit sockets (center-left) ---
    # DevKitC-1: 2x 1x20 header sockets, 25.4mm apart
    master_cx = ox + 55
    master_y = oy + 34
    layout['J1'] = (master_cx - 12.7, master_y, 0)  # Left 1x20
    layout['J2'] = (master_cx + 12.7, master_y, 0)  # Right 1x20

    # --- Slave DevKit sockets (2x2 grid, bottom-left) ---
    # Each slave: pair of 1x8 headers, ~24mm apart
    # 1x8 headers span 7*2.54 = 17.78mm. Need 22mm+ between rows.
    slave_pairs = [
        ('J8',  'J15', ox + 5,  oy + 54),   # Slave A (top-left)
        ('J9',  'J16', ox + 48, oy + 54),   # Slave B (top-right)
        ('J10', 'J17', ox + 5,  oy + 78),   # Slave C (bottom-left)
        ('J11', 'J18', ox + 48, oy + 78),   # Slave D (bottom-right)
    ]
    for left, right, sx, sy in slave_pairs:
        layout[left]  = (sx,      sy, 0)
        layout[right] = (sx + 24, sy, 0)

    # ================================================================
    # ZONE B — ADC ANALOG (right half, top, x: ox+95 to ox+200, y: oy to oy+42)
    # ================================================================

    # J_AFE on right edge (cable from preamp board)
    layout['J3'] = (ox + bw - 5, oy + 20, 90)  # Rotated vertical on right edge

    # ES8388 #1 (channels 1-4)
    layout['U1'] = (ox + 120, oy + 16, 0)
    # ES8388 #2 (channels 5-8)
    layout['U2'] = (ox + 150, oy + 16, 0)

    # ================================================================
    # ZONE C — DAC / OUTPUT ANALOG (right half, bottom, y: oy+45 to oy+100)
    # ================================================================

    # HT8988A DAC codec
    layout['U5'] = (ox + 100, oy + 52, 0)

    # NE5532 summing amps — spread more
    layout['U9']  = (ox + 100, oy + 70, 0)      # Summing amp (L+R inverting)
    layout['U10'] = (ox + 100, oy + 84, 0)      # Output buffer (L+R follower)

    # CD4052B analog muxes — more space between
    layout['U7'] = (ox + 138, oy + 55, 0)       # Mux #1 (primary routing)
    layout['U8'] = (ox + 138, oy + 75, 0)       # Mux #2 (wet/dry split)

    # Audio jacks on right edge — more vertical spread
    layout['J7']  = (ox + bw - 4, oy + 50, 0)   # Headphone 3.5mm jack
    layout['J12'] = (ox + bw - 4, oy + 68, 0)   # Line output 3.5mm jack

    # Volume pots near headphone jack — move left to avoid jack overlap
    layout['RV1'] = (ox + bw - 26, oy + 48, 0)  # HP volume L
    layout['RV2'] = (ox + bw - 26, oy + 64, 0)  # HP volume R

    # Output headers (6.35mm jack placeholders) on bottom-right
    layout['J13'] = (ox + bw - 6, oy + 78, 0)   # J_OUT_L
    layout['J14'] = (ox + bw - 6, oy + 86, 0)   # J_OUT_R

    # Footswitch connectors on bottom edge of analog zone
    layout['J5'] = (ox + 108, oy + bh - 5, 0)   # FS1
    layout['J6'] = (ox + 125, oy + bh - 5, 0)   # FS2

    # ================================================================
    # Mounting holes at 4 corners
    # ================================================================
    mh_refs = sorted([r for r in fps if r.startswith('H')])
    mh_positions = [
        (ox + 4, oy + 4),
        (ox + bw - 4, oy + 4),
        (ox + 40, oy + bh - 4),      # H3: between slave A/B columns (clear of pins)
        (ox + bw - 4, oy + bh - 4),  # H4: right side (clear of headers)
    ]
    for i, ref in enumerate(mh_refs[:4]):
        layout[ref] = (mh_positions[i][0], mh_positions[i][1], 0)

    # ================================================================
    # Passive component clustering (net-based, near parent ICs)
    # ================================================================
    anchor_positions = {ref: (x, y) for ref, (x, y, _) in layout.items()
                        if ref.startswith(('U', 'J', 'FB', 'D'))}

    assignments = assign_passives_to_anchors(fps, nets, anchor_positions)

    print(f"  Passive assignments:")
    for k, v in sorted(assignments.items()):
        print(f"    {k}: {sorted(v)}")

    for anchor_ref, passive_list in assignments.items():
        if anchor_ref == 'UNASSIGNED' or anchor_ref not in layout:
            continue
        ax, ay, _ = layout[anchor_ref]
        # Place passives to the right of anchor, or left if near right edge
        if ax > ox + bw - 35:
            place_passives_near_anchor(ax, ay, passive_list, layout, x_dir=-1)
        else:
            place_passives_near_anchor(ax, ay, passive_list, layout, x_dir=1)

    # Handle unassigned passives — place in available space
    unassigned = assignments.get('UNASSIGNED', [])
    if unassigned:
        print(f"  Unassigned passives: {sorted(unassigned)}")
        for i, ref in enumerate(sorted(unassigned)):
            col = i % 8
            row = i // 8
            layout[ref] = (ox + 95 + col * 4, oy + 38 + row * 3, 0)

    # Any remaining unplaced components
    remaining = [r for r in fps if r not in layout]
    if remaining:
        print(f"  Remaining unplaced: {remaining}")
        for i, ref in enumerate(remaining):
            layout[ref] = (ox + 5 + (i % 10) * 8, oy + bh - 12 + (i // 10) * 5, 0)

    place_components_grid(board, fps, layout)
    add_board_outline(board, ox, oy, bw, bh, corner_radius=2)

    # Ground copper pours
    # DGND on F.Cu and B.Cu (full board — connects through ferrite to AGND)
    add_ground_pour(board, "DGND", "F.Cu", ox, oy, bw, bh)
    add_ground_pour(board, "DGND", "B.Cu", ox, oy, bw, bh)
    # AGND pour on inner layer In2.Cu for analog right half
    add_ground_pour(board, "AGND", "In2.Cu", ox + 90, oy, bw - 90, bh)

    out_path = str(board_dir / "layout.kicad_pcb")
    pcbnew.SaveBoard(out_path, board)
    print(f"  Saved: {out_path}")


def layout_preamp():
    """Layout the 8-channel preamp/AFE board."""
    board_dir = BOARDS_DIR / "preamp" / "layout"
    net_path = board_dir / "default.net"

    if not net_path.exists():
        print("  Preamp netlist not found, skipping")
        return

    print("  Parsing netlist...")
    components, nets = parse_netlist(net_path)
    print(f"  Found {len(components)} components, {len(nets)} nets")

    board, fps = create_board("preamp", components, nets, {'layers': 4})

    # Preamp board: ~160x80mm (large, 165 components, 8 channels + VGND)
    bw, bh = 160, 80
    ox, oy = 10, 10

    layout = {}

    # Group components by channel (1-8)
    # Each channel has: input coupling cap, buffer opamp, gain opamp, filter opamp,
    # trimpot, various R/C, mono jack
    channel_width = 18  # mm per channel

    # Op-amps (NE5532): arrange by function
    opamp_refs = sorted([r for r in fps if r.startswith('U')])

    # Input headers along left edge
    input_refs = sorted([r for r in fps if 'J_IN' in fps[r].GetValue()])
    for i, ref in enumerate(input_refs):
        layout[ref] = (ox + 3, oy + 8 + i * 8, 0)

    # Mono jacks along top edge (buffered direct outputs)
    jack_refs = sorted([r for r in fps if 'mono' in fps[r].GetFPIDAsString().lower() or 'JACK' in fps[r].GetValue().upper()])
    for i, ref in enumerate(jack_refs):
        layout[ref] = (ox + 20 + i * channel_width, oy + 3, 0)

    # Output connector on right
    for ref in fps:
        val = fps[ref].GetValue()
        if 'J_OUT' in val:
            layout[ref] = (ox + bw - 5, oy + bh/2, 0)
        elif 'J_PWR' in val:
            layout[ref] = (ox + bw - 5, oy + 8, 0)

    # Trimpots in a row
    trim_refs = sorted([r for r in fps if 'trim' in fps[r].GetFPIDAsString().lower() or 'TRIM' in fps[r].GetValue().upper()])
    for i, ref in enumerate(trim_refs):
        layout[ref] = (ox + 20 + i * channel_width, oy + bh - 8, 0)

    # Op-amps arranged in rows by function
    # Row 1: Input buffers (y=20)
    # Row 2: Gain stages (y=35)
    # Row 3: Filter stages (y=50)
    # Row 4: Direct output buffers (y=65)
    for i, ref in enumerate(opamp_refs):
        row = i // 8 if len(opamp_refs) > 8 else 0
        col = i % 8
        y_base = oy + 20 + row * 15
        layout[ref] = (ox + 20 + col * channel_width, y_base, 0)

    # Passive components near their associated channels
    cap_refs = sorted([r for r in fps if r.startswith('C') and r not in layout])
    for i, ref in enumerate(cap_refs):
        ch = i % 8
        row = i // 8
        layout[ref] = (ox + 22 + ch * channel_width, oy + 15 + row * 5, 0)

    res_refs = sorted([r for r in fps if r.startswith('R') and r not in layout])
    for i, ref in enumerate(res_refs):
        ch = i % 8
        row = i // 8
        layout[ref] = (ox + 24 + ch * channel_width, oy + 15 + row * 5, 0)

    # Mounting holes
    mh_refs = sorted([r for r in fps if r.startswith('H')])
    mh_positions = [(ox + 3, oy + 3), (ox + bw - 3, oy + 3), (ox + 3, oy + bh - 3), (ox + bw - 3, oy + bh - 3)]
    for i, ref in enumerate(mh_refs[:4]):
        layout[ref] = (mh_positions[i][0], mh_positions[i][1], 0)

    # Remaining
    remaining = [r for r in fps if r not in layout]
    for i, ref in enumerate(remaining):
        layout[ref] = (ox + 15 + (i % 12) * 12, oy + bh - 15 + (i // 12) * 5, 0)

    place_components_grid(board, fps, layout)
    add_board_outline(board, ox, oy, bw, bh, corner_radius=2)
    add_ground_pour(board, "GND", "F.Cu", ox, oy, bw, bh)
    add_ground_pour(board, "GND", "B.Cu", ox, oy, bw, bh)

    out_path = str(board_dir / "layout.kicad_pcb")
    pcbnew.SaveBoard(out_path, board)
    print(f"  Saved: {out_path}")




def main():
    print("=" * 60)
    print("Auto-Layout for Preamp-Zener PCB Boards")
    print("=" * 60)

    boards = [
        ("MAIN", layout_main),
        ("Preamp", layout_preamp),
    ]

    for name, layout_fn in boards:
        print(f"\n--- {name} Board ---")
        try:
            layout_fn()
        except Exception as e:
            print(f"  ERROR: {e}")
            import traceback
            traceback.print_exc()

    print("\n" + "=" * 60)
    print("Auto-layout complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
