#!/usr/bin/env python3
"""
Auto-layout script for preamp-zener PCB boards.
Reads netlists generated by `pcb layout`, imports footprints from KiCad libraries,
places components, adds board outlines and copper pours, then saves.
"""

import json
import math
import os
import re
import pcbnew
from pathlib import Path

BOARDS_DIR = Path(__file__).parent / "boards"
KICAD_FP_DIR = Path("/usr/share/kicad/footprints")
LOCAL_FP_DIR = Path(__file__).parent / "footprints"
CACHE_FP_DIR = Path(__file__).parent / ".pcb/cache/gitlab.com/kicad/libraries/kicad-footprints/9.0.3"

# Map footprint library names from netlist to actual .pretty directories
FPLIB_MAP = {
    "MountingHole_2.2mm_M2_DIN965_Pad_TopBottom": ("MountingHole.pretty", "MountingHole_2.2mm_M2_DIN965_Pad_TopBottom"),
    "MountingHole_2.2mm_M2_Pad": ("MountingHole.pretty", "MountingHole_2.2mm_M2_Pad"),
    "PinHeader_1x08_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_1x08_P2.54mm_Vertical"),
    "PinSocket_1x08_P2.54mm_Vertical": ("Connector_PinSocket_2.54mm.pretty", "PinSocket_1x08_P2.54mm_Vertical"),
    "PinHeader_1x02_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_1x02_P2.54mm_Vertical"),
    "PinHeader_2x05_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_2x05_P2.54mm_Vertical"),
    "PinHeader_2x06_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_2x06_P2.54mm_Vertical"),
    "PinHeader_1x20_P2.54mm_Vertical": ("Connector_PinHeader_2.54mm.pretty", "PinHeader_1x20_P2.54mm_Vertical"),
    "PinSocket_1x20_P2.54mm_Vertical": ("Connector_PinSocket_2.54mm.pretty", "PinSocket_1x20_P2.54mm_Vertical"),
    "ESP32-S3-DevKitC": ("Espressif.pretty", "ESP32-S3-DevKitC"),
}


def find_footprint_lib(fpid_str):
    """Find the .pretty directory and footprint name for a given FPID string.
    Handles both 'lib:footprint' and plain 'footprint' formats."""
    if ":" in fpid_str:
        lib_name, fp_name = fpid_str.split(":", 1)
    else:
        lib_name = fpid_str
        fp_name = fpid_str

    # Check our explicit map — prioritize system KiCad 7 libs over cache (KiCad 9 format)
    if fp_name in FPLIB_MAP:
        pretty_dir, actual_fp = FPLIB_MAP[fp_name]
        for base in [LOCAL_FP_DIR, KICAD_FP_DIR, CACHE_FP_DIR]:
            lib_path = base / pretty_dir
            if lib_path.exists() and (lib_path / f"{actual_fp}.kicad_mod").exists():
                return str(lib_path), actual_fp

    # Try to find by searching .pretty directories — local first, then system
    for base in [LOCAL_FP_DIR, KICAD_FP_DIR, CACHE_FP_DIR]:
        if not base.exists():
            continue
        for pretty in base.iterdir():
            if pretty.suffix == ".pretty":
                fp_file = pretty / f"{fp_name}.kicad_mod"
                if fp_file.exists():
                    return str(pretty), fp_name

    return None, None


def parse_netlist(net_path):
    """Parse KiCad netlist (.net) file to extract components and nets."""
    with open(net_path, 'r') as f:
        content = f.read()

    components = []
    # Extract component entries — find each (comp ...) block
    comp_start = re.compile(r'\(comp \(ref "([^"]+)"\)')
    for m in comp_start.finditer(content):
        ref = m.group(1)
        # Find balanced closing paren for this comp block
        start_pos = m.start()
        depth = 0
        end_pos = start_pos
        for i in range(start_pos, len(content)):
            if content[i] == '(':
                depth += 1
            elif content[i] == ')':
                depth -= 1
                if depth == 0:
                    end_pos = i + 1
                    break
        comp_block = content[start_pos:end_pos]

        # Extract value and footprint
        val_m = re.search(r'\(value "([^"]+)"\)', comp_block)
        fp_m = re.search(r'\(footprint "([^"]+)"\)', comp_block)
        value = val_m.group(1) if val_m else ""
        footprint = fp_m.group(1) if fp_m else ""

        # Extract zen name from sheetpath (preserves .zen name= parameter)
        sheet_m = re.search(r'\(sheetpath \(names "([^"]+)"\)', comp_block)
        zen_name = ""
        if sheet_m:
            zen_name = sheet_m.group(1).split('.')[0]  # Strip component suffix

        components.append({
            'ref': ref,
            'value': value,
            'footprint': footprint,
            'zen_name': zen_name,
        })

    # Extract nets — use paren-balanced extraction for multi-node nets
    nets = []
    node_pattern = re.compile(r'\(node \(ref "([^"]+)"\) \(pin "([^"]+)"\)')
    # Find each (net ...) block by balancing parentheses
    net_start = re.compile(r'\(net \(code "\d+"\) \(name "([^"]+)"\)')
    for m in net_start.finditer(content):
        net_name = m.group(1)
        # Find balanced closing paren from start of (net ...)
        start_pos = m.start()
        depth = 0
        end_pos = start_pos
        for i in range(start_pos, len(content)):
            if content[i] == '(':
                depth += 1
            elif content[i] == ')':
                depth -= 1
                if depth == 0:
                    end_pos = i + 1
                    break
        net_block = content[start_pos:end_pos]
        nodes = [(n.group(1), n.group(2)) for n in node_pattern.finditer(net_block)]
        nets.append({'name': net_name, 'nodes': nodes})

    return components, nets


def create_board(board_name, components, nets, board_config):
    """Create a KiCad PCB with placed components."""
    board = pcbnew.BOARD()

    # Set title
    title_block = board.GetTitleBlock()
    title_block.SetTitle(board_name)

    # Set design rules
    ds = board.GetDesignSettings()
    ds.SetCopperLayerCount(board_config.get('layers', 2))
    ds.m_TrackMinWidth = pcbnew.FromMM(0.2)
    ds.m_ViasMinSize = pcbnew.FromMM(0.45)
    ds.m_ViasMinDrill = pcbnew.FromMM(0.2)
    ds.m_CopperEdgeClearance = pcbnew.FromMM(0.25)

    # Set default track width and clearance
    ds.m_MinClearance = pcbnew.FromMM(0.2)

    # Load and place footprints
    placed_fps = {}
    for comp in components:
        ref = comp['ref']
        fpid = comp['footprint']

        lib_path, fp_name = find_footprint_lib(fpid)
        if lib_path is None:
            print(f"  WARNING: Could not find footprint for {ref}: {fpid}")
            continue

        try:
            fp = pcbnew.FootprintLoad(lib_path, fp_name)
        except Exception as e:
            print(f"  WARNING: Failed to load {fp_name} from {lib_path}: {e}")
            continue

        fp.SetReference(ref)
        fp.SetValue(comp['value'])
        board.Add(fp)
        placed_fps[ref] = fp

    # Create nets and assign to pads
    netinfo = board.GetNetInfo()
    for net_entry in nets:
        net_name = net_entry['name']
        net_item = pcbnew.NETINFO_ITEM(board, net_name)
        board.Add(net_item)

    # Refresh net info after adding all nets
    netinfo = board.GetNetInfo()
    nets_by_name = netinfo.NetsByName()

    for net_entry in nets:
        net_name = net_entry['name']
        if not nets_by_name.has_key(net_name):
            continue
        net_obj = nets_by_name[net_name]
        for ref, pin in net_entry['nodes']:
            if ref in placed_fps:
                fp = placed_fps[ref]
                for pad in fp.Pads():
                    if pad.GetNumber() == pin:
                        pad.SetNet(net_obj)
                        break

    return board, placed_fps


def mm_pos(x, y):
    """Create a VECTOR2I position from mm coordinates."""
    return pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y))


def place_components_grid(board, placed_fps, layout_spec):
    """Place components according to layout specification."""
    for ref, (x, y, rot) in layout_spec.items():
        if ref in placed_fps:
            fp = placed_fps[ref]
            fp.SetPosition(mm_pos(x, y))
            fp.SetOrientationDegrees(rot)


def add_board_outline(board, x, y, w, h, corner_radius=0):
    """Add rectangular board outline on Edge.Cuts layer."""
    edge_layer = board.GetLayerID("Edge.Cuts")

    # Simple rectangle outline (corner_radius ignored for API compatibility)
    for (x1, y1, x2, y2) in [
        (x, y, x + w, y),
        (x + w, y, x + w, y + h),
        (x + w, y + h, x, y + h),
        (x, y + h, x, y),
    ]:
        line = pcbnew.PCB_SHAPE(board)
        line.SetShape(pcbnew.SHAPE_T_SEGMENT)
        line.SetStart(mm_pos(x1, y1))
        line.SetEnd(mm_pos(x2, y2))
        line.SetLayer(edge_layer)
        line.SetWidth(pcbnew.FromMM(0.1))
        board.Add(line)


def add_silkscreen_labels(board, components, placed_fps, layout):
    """Add descriptive silkscreen text labels near labeled components.

    Maps zen names (from .zen name= parameter, preserved in netlist sheetpath)
    to human-readable silkscreen labels. Small passives are skipped.
    """
    silk_layer = board.GetLayerID("F.Silkscreen")

    # Zen name -> silkscreen label mapping
    # Defined here but derived from .zen name= parameters
    ZEN_LABELS = {
        # MAIN board connectors
        'J_USB': 'USB',
        'J_BAT': 'BATTERY',
        'J_AFE': 'PREAMP CABLE',
        'J_HP': 'HEADPHONE',
        'J_LINE': 'LINE OUT',
        'J_OUT_L': 'MAIN OUT L',
        'J_OUT_R': 'MAIN OUT R',
        'J_FS1': 'FOOTSWITCH 1',
        'J_FS2': 'FOOTSWITCH 2',
        # MAIN board slave sockets
        'J_LEFT_A': 'SLAVE A L',
        'J_RIGHT_A': 'SLAVE A R',
        'J_LEFT_B': 'SLAVE B L',
        'J_RIGHT_B': 'SLAVE B R',
        'J_LEFT_C': 'SLAVE C L',
        'J_RIGHT_C': 'SLAVE C R',
        'J_LEFT_D': 'SLAVE D L',
        'J_RIGHT_D': 'SLAVE D R',
        # MAIN board master ESP32 (single 44-pin Espressif footprint)
        'DEVKIT_MASTER': 'MASTER ESP32',
        # MAIN board volume pots
        'RV_HPL': 'HP VOL L',
        'RV_HPR': 'HP VOL R',
        # MAIN board ICs
        'U_CHG': 'CHARGER',
        'U_AVDD': 'AVDD LDO',
        'U_DVDD': 'DVDD LDO',
        'U_ADC1': 'ADC CH1+2',
        'U_ADC2': 'ADC CH3+4',
        'U_ADC3': 'ADC CH5+6 / DAC',
        'U_ADC4': 'ADC CH7+8',
        'U_SUM': 'SUMMING AMP',
        'U_OUTBUF': 'OUT BUFFER',
        'U_MUX1': 'MUX 1',
        'U_MUX2': 'MUX 2',
        # Preamp board connectors
        'J_OUT': 'TO MAIN',
        'J_PWR': 'POWER IN',
        'U_VGND': 'VGND',
    }
    # Preamp pickup inputs and direct outputs (generated in loop)
    for i in range(1, 9):
        ZEN_LABELS[f'J_IN{i}'] = f'PICKUP {i}'
        ZEN_LABELS[f'J_DOUT{i}'] = f'DIR OUT {i}'
        ZEN_LABELS[f'RV_F{i}'] = f'GAIN {i}'

    count = 0
    for comp in components:
        ref = comp['ref']
        zen_name = comp.get('zen_name', '')

        if ref not in placed_fps or ref not in layout:
            continue

        # Look up label from zen name
        text_str = ZEN_LABELS.get(zen_name, '')
        if not text_str:
            continue

        x, y, rot = layout[ref]

        # Position and rotation depend on zen_name category
        if zen_name.startswith('J_DOUT'):
            # Direct outputs: label to the right of pins
            label_x, label_y = x + 3, y
            label_rot = 0
            h_justify = pcbnew.GR_TEXT_H_ALIGN_LEFT
        elif zen_name.startswith('J_IN'):
            # Pickup inputs: label above, rotated 90° CCW
            label_x, label_y = x, y - 6
            label_rot = 90
            h_justify = pcbnew.GR_TEXT_H_ALIGN_CENTER
        elif zen_name.startswith('RV_F'):
            # Gain trimpots: label to the left
            label_x, label_y = x - 5, y
            label_rot = 0
            h_justify = pcbnew.GR_TEXT_H_ALIGN_RIGHT
        else:
            # Default: below the component
            label_x, label_y = x, y + 3
            label_rot = 0
            h_justify = pcbnew.GR_TEXT_H_ALIGN_CENTER

        text = pcbnew.PCB_TEXT(board)
        text.SetText(text_str)
        text.SetLayer(silk_layer)
        text.SetPosition(mm_pos(label_x, label_y))
        text.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(1.0), pcbnew.FromMM(1.0)))
        text.SetTextThickness(pcbnew.FromMM(0.15))
        text.SetHorizJustify(h_justify)
        if label_rot != 0:
            text.SetTextAngleDegrees(label_rot)
        board.Add(text)
        count += 1

    print(f"  Added {count} silkscreen labels")


def add_ground_pour(board, net_name, layer_name, x, y, w, h):
    """Add a copper pour (zone) for ground or power plane."""
    netinfo = board.GetNetInfo()
    nets_by_name = netinfo.NetsByName()
    if not nets_by_name.has_key(net_name):
        print(f"  WARNING: Net '{net_name}' not found for copper pour")
        return

    net = nets_by_name[net_name]
    layer_id = board.GetLayerID(layer_name)

    zone = pcbnew.ZONE(board)
    zone.SetNet(net)
    zone.SetLayer(layer_id)
    zone.SetIsRuleArea(False)
    zone.SetDoNotAllowTracks(False)
    zone.SetDoNotAllowVias(False)
    zone.SetDoNotAllowPads(False)
    zone.SetDoNotAllowCopperPour(False)

    # Create outline
    outline = zone.Outline()
    outline.NewOutline()
    outline.Append(pcbnew.FromMM(x), pcbnew.FromMM(y))
    outline.Append(pcbnew.FromMM(x + w), pcbnew.FromMM(y))
    outline.Append(pcbnew.FromMM(x + w), pcbnew.FromMM(y + h))
    outline.Append(pcbnew.FromMM(x), pcbnew.FromMM(y + h))

    # Set zone properties
    zone.SetMinThickness(pcbnew.FromMM(0.25))
    zone.SetThermalReliefGap(pcbnew.FromMM(0.5))
    zone.SetThermalReliefSpokeWidth(pcbnew.FromMM(0.5))

    board.Add(zone)


def hide_fab_layers(pro_path):
    """Hide F.Fab and B.Fab layers in the .kicad_pro project file."""
    with open(pro_path, 'r') as f:
        proj = json.load(f)

    # KiCad layer IDs: F.Fab=35, B.Fab=33
    # visible_layers is a hex bitmask string; all layers on = 0xffffffffffffffff
    all_on = (1 << 64) - 1
    fab_front = 1 << 35
    fab_back = 1 << 33
    mask = all_on & ~fab_front & ~fab_back
    # KiCad format: "0x00000000_HHHHHHHH_HHHHHHHH_HHHHHHHH" (128-bit, underscore-separated)
    hex_str = f"0x00000000_00000000_{(mask >> 32) & 0xffffffff:08x}_{mask & 0xffffffff:08x}"

    proj.setdefault('board', {})
    proj['board']['visible_layers'] = hex_str

    with open(pro_path, 'w') as f:
        json.dump(proj, f, indent=2)
    print(f"  Hidden F.Fab/B.Fab in {pro_path}")


# ============================================================
# Net-based passive clustering helpers
# ============================================================

def build_net_map(nets):
    """Build ref -> set(net_names) and net_name -> set(refs) maps."""
    ref_to_nets = {}
    net_to_refs = {}
    for net_entry in nets:
        net_name = net_entry['name']
        for ref, pin in net_entry['nodes']:
            ref_to_nets.setdefault(ref, set()).add(net_name)
            net_to_refs.setdefault(net_name, set()).add(ref)
    return ref_to_nets, net_to_refs


POWER_NETS = {'AGND', 'DGND', 'AVDD', 'DVDD', 'VBUS', 'VBAT', 'VBAT_RAW', 'GND', 'VGND'}


def assign_passives_to_anchors(fps, nets, anchor_positions):
    """Assign each passive to nearest anchor it shares signal nets with."""
    ref_to_nets, net_to_refs = build_net_map(nets)
    anchor_refs = set(anchor_positions.keys())
    assignments = {}  # anchor_ref -> [passive_refs]
    _power_rr_counters = {}  # round-robin counters for power domain distribution

    for ref in fps:
        if ref in anchor_refs or ref.startswith(('H', 'RV')):
            continue
        if not ref.startswith(('R', 'C')):
            continue

        my_nets = ref_to_nets.get(ref, set())
        my_signal_nets = my_nets - POWER_NETS

        # Find anchor sharing the most signal nets
        best_anchor = None
        best_score = 0
        for net_name in my_signal_nets:
            for other_ref in net_to_refs.get(net_name, set()):
                if other_ref in anchor_refs and other_ref != ref:
                    score = len(my_signal_nets & ref_to_nets.get(other_ref, set()))
                    if score > best_score:
                        best_score = score
                        best_anchor = other_ref

        # Fallback: find anchor via shared power nets (for decoupling caps)
        if best_anchor is None:
            # Try to find via transitive signal connections (passive shares net with another
            # passive that connects to an anchor)
            for net_name in my_signal_nets:
                for mid_ref in net_to_refs.get(net_name, set()):
                    if mid_ref != ref and mid_ref.startswith(('R', 'C')):
                        mid_signal = ref_to_nets.get(mid_ref, set()) - POWER_NETS
                        for mn in mid_signal:
                            for ar in net_to_refs.get(mn, set()):
                                if ar in anchor_refs:
                                    best_anchor = ar
                                    break
                            if best_anchor:
                                break
                    if best_anchor:
                        break
                if best_anchor:
                    break

        # Last resort: distribute power-only caps round-robin across ICs in domain
        if best_anchor is None:
            my_power = my_nets & POWER_NETS
            if 'AVDD' in my_power or 'AGND' in my_power:
                analog_ics = [c for c in ['U2', 'U3', 'U4', 'U5', 'U6', 'U11', 'U12', 'U9', 'U10']
                              if c in anchor_refs]
                if analog_ics:
                    idx = _power_rr_counters.get('analog', 0) % len(analog_ics)
                    best_anchor = analog_ics[idx]
                    _power_rr_counters['analog'] = idx + 1
            elif 'DVDD' in my_power or 'DGND' in my_power:
                digital_ics = [c for c in ['U8', 'U7', 'U1', 'U2', 'U3', 'U4', 'U5']
                               if c in anchor_refs]
                if digital_ics:
                    idx = _power_rr_counters.get('digital', 0) % len(digital_ics)
                    best_anchor = digital_ics[idx]
                    _power_rr_counters['digital'] = idx + 1

        if best_anchor is None:
            best_anchor = 'UNASSIGNED'
        assignments.setdefault(best_anchor, []).append(ref)

    return assignments


def place_passives_near_anchor(anchor_x, anchor_y, passive_refs, layout, x_dir=1):
    """Place passive components clustered around an anchor position."""
    n = len(passive_refs)
    # Adaptive columns: more passives = wider spread
    cols = min(5, max(2, n // 2))
    spacing_x = 4.5 * x_dir
    spacing_y = 3.5
    start_x = anchor_x + 6 * x_dir
    start_y = anchor_y - min(3, (n // cols) * 1.5)
    for i, ref in enumerate(sorted(passive_refs)):
        col = i % cols
        row = i // cols
        x = start_x + col * spacing_x
        y = start_y + row * spacing_y
        layout[ref] = (x, y, 0)


def _footprint_aabb(ref, lx, ly, rot, fp_str=''):
    """Return absolute (xmin, xmax, ymin, ymax) AABB for a component.

    Uses actual F.CrtYd dimensions from KiCad footprint files for known parts,
    with 0.15mm manufacturing clearance margin on all sides (courtyard already
    includes its own margin beyond pads).
    Rotation is KiCad degrees (CCW positive, Y-axis pointing down).
    """
    margin = 0.15
    native = None

    # Footprint-string-based detection first (board-independent)
    if 'USB_C' in fp_str or 'USB4085' in fp_str:
        # USB-C receptacle (GCT USB4085): large asymmetric footprint
        # Native (0° rotation): ref point near top-left, body extends right and down
        native = (-2.4, 8.3, -1.2, 9.2)
    elif 'Jack_3.5mm' in fp_str or 'SJ1-3523N' in fp_str:
        # CUI SJ1-3523N Horizontal 3.5mm jack: F.CrtYd (-6.25,-7.95) to (6.25,6.55)
        native = (-6.25, 6.25, -7.95, 6.55)
    elif 'SOT-223' in fp_str:
        # SOT-223-3 (e.g. AP2114H LDO): ~8.8x7.3mm courtyard
        native = (-4.5, 4.5, -3.8, 3.7)
    elif 'Bourns_3314J' in fp_str:
        # Bourns 3314J Vertical SMD: F.CrtYd (-2.5,-3.25) to (2.5,3.25)
        native = (-2.5, 2.5, -3.25, 3.25)
    elif 'Bourns_3296' in fp_str:
        # Bourns 3296W Vertical: ~5x11mm courtyard
        native = (-2.5, 2.5, -5.5, 5.5)
    elif 'PinHeader_2x' in fp_str or 'PinSocket_2x' in fp_str:
        if '2x05' in fp_str:
            native = (-2.54, 2.54, -1.27, 11.43)
        elif '2x06' in fp_str:
            native = (-2.54, 2.54, -1.27, 13.97)
        else:
            native = (-2.54, 2.54, -1.27, 11.43)
    elif 'PinHeader_1x' in fp_str or 'PinSocket_1x' in fp_str:
        if '1x20' in fp_str:
            native = (-1.27, 1.27, -1.27, 49.53)
        elif '1x08' in fp_str:
            native = (-1.27, 1.27, -1.27, 19.05)
        elif '1x03' in fp_str:
            native = (-1.27, 1.27, -1.27, 6.35)
        elif '1x02' in fp_str:
            native = (-1.27, 1.27, -1.27, 3.81)
        else:
            native = (-1.27, 1.27, -1.27, 3.81)

    # Fall back to ref-based heuristics
    if native is None:
        if ref.startswith('RV'):
            # Alps RK09K Vertical: F.CrtYd (-1.15,-4.15) to (13.25,9.15)
            native = (-1.15, 13.25, -4.15, 9.15)
        elif ref.startswith('U'):
            if 'SOIC-16' in fp_str or '3.9x9.9' in fp_str:
                # SOIC-16_3.9x9.9mm: courtyard roughly ±4.2 x ±5.7 (symmetric)
                native = (-4.2, 4.2, -5.7, 5.7)
            elif 'QFN-28' in fp_str and '4x4mm' in fp_str:
                # QFN-28-1EP_4x4mm_P0.4mm_EP2.4x2.4mm: courtyard ~5.1x5.1mm
                native = (-2.55, 2.55, -2.55, 2.55)
            else:
                # SOIC-8 and other small ICs: roughly ±3.5 symmetric
                native = (-3.5, 3.5, -3.5, 3.5)
        elif ref.startswith(('FB', 'D')):
            # Ferrite / diode: ~4x3mm
            native = (-2.0, 2.0, -1.5, 1.5)
        else:
            # Passives — use footprint string to determine size
            if '0805' in fp_str:
                # 0805 courtyard: 2.7x1.75mm
                native = (-1.35, 1.35, -0.875, 0.875)
            elif '0603' in fp_str:
                # 0603 courtyard: 2.2x1.2mm
                native = (-1.1, 1.1, -0.6, 0.6)
            else:
                # 0402 courtyard: 1.4x0.8mm
                native = (-0.7, 0.7, -0.4, 0.4)

    xn_min, xn_max, yn_min, yn_max = native
    # Rotate the four corners and compute new AABB
    # KiCad Y-down, CCW positive: rx = x*cos(θ) + y*sin(θ), ry = -x*sin(θ) + y*cos(θ)
    theta = math.radians(rot)
    cos_t, sin_t = math.cos(theta), math.sin(theta)
    rxs, rys = [], []
    for x, y in [(xn_min, yn_min), (xn_max, yn_min), (xn_max, yn_max), (xn_min, yn_max)]:
        rxs.append(x * cos_t + y * sin_t + lx)
        rys.append(-x * sin_t + y * cos_t + ly)

    return (min(rxs) - margin, max(rxs) + margin, min(rys) - margin, max(rys) + margin)


def place_passives_right_section(right_assignments, layout, ox, oy, bw, bh, fps=None, x_min_offset=70, bounds=None):
    """Place passives near their parent anchor, avoiding overlaps.

    Uses AABB collision detection with actual footprint courtyard dimensions so
    asymmetric parts (potentiometers, horizontal jacks) are correctly handled.

    Args:
        right_assignments: dict of anchor_ref -> [passive_refs]
        layout: shared layout dict (modified in place)
        fps: dict of ref -> footprint object (used to determine passive sizes)
        x_min_offset: left boundary offset from ox (default 70 for main board right section)
        bounds: optional (x_min, x_max, y_min, y_max) to override calculated bounds
    """
    # Board bounds, inset from board edge
    if bounds:
        x_min, x_max, y_min, y_max = bounds
    else:
        x_min, x_max = ox + x_min_offset, ox + bw - 3
        y_min, y_max = oy + 2, oy + bh - 2

    # Candidate grid with 2.0mm step — AABB check handles per-footprint clearance
    # so mixed 0402/0603/0805 are correctly spaced regardless of grid density
    step = 2.0
    all_candidates = []
    x = x_min
    while x <= x_max:
        y = y_min
        while y <= y_max:
            all_candidates.append((x, y))
            y += step
        x += step

    # Seed occupied list with AABBs for every already-placed component (left AND right sections)
    occupied = []  # list of (xmin, xmax, ymin, ymax)
    for ref, (lx, ly, rot) in layout.items():
        fp_str = fps[ref].GetFPIDAsString() if fps and ref in fps else ''
        occupied.append(_footprint_aabb(ref, lx, ly, rot, fp_str))

    # Moat-crossing routing corridors: vias and F.Cu stubs.
    # Passives must not be placed here or they'll short with routed vias.
    ROUTING_CORRIDORS = [
        (74.0, 82.5, 25.0, 49.5),   # ES8388 I2S/I2C moat-crossing routes + stitching vias
        (71.0, 88.5, 59.0, 77.0),   # MUX control moat-crossing routes
    ]

    def is_free(cx, cy, fp_str):
        """Return True if placing a passive at (cx,cy) doesn't overlap any occupied AABB
        or the moat-crossing routing corridors."""
        cmin_x, cmax_x, cmin_y, cmax_y = _footprint_aabb('passive', cx, cy, 0, fp_str)
        # Check routing corridor exclusions
        for rc in ROUTING_CORRIDORS:
            if cmin_x < rc[1] and cmax_x > rc[0] and cmin_y < rc[3] and cmax_y > rc[2]:
                return False
        for omin_x, omax_x, omin_y, omax_y in occupied:
            if cmin_x < omax_x and cmax_x > omin_x and cmin_y < omax_y and cmax_y > omin_y:
                return False
        return True

    def dist_sq(x1, y1, x2, y2):
        return (x1 - x2) ** 2 + (y1 - y2) ** 2

    # Process anchors smallest-group-first so each anchor secures a nearby slot before
    # large groups (e.g. U1 with 15 passives) fill the nearby candidates.
    ordered_anchors = sorted(
        right_assignments.keys(),
        key=lambda a: (len(right_assignments[a]), layout[a][1] if a in layout else 999)
    )

    placed = 0
    for anchor_ref in ordered_anchors:
        passive_list = right_assignments[anchor_ref]
        if anchor_ref not in layout:
            continue
        ax, ay, _ = layout[anchor_ref]

        # Sort candidates by distance to this anchor
        sorted_candidates = sorted(all_candidates, key=lambda c: dist_sq(c[0], c[1], ax, ay))

        for ref in sorted(passive_list):
            fp_str = fps[ref].GetFPIDAsString() if fps and ref in fps else ''

            # Find nearest free candidate to anchor
            for cx, cy in sorted_candidates:
                if is_free(cx, cy, fp_str):
                    layout[ref] = (cx, cy, 0)
                    occupied.append(_footprint_aabb('passive', cx, cy, 0, fp_str))
                    placed += 1
                    break
            else:
                # No free slot — overflow at right edge below board area
                col = placed % 10
                row = placed // 10
                layout[ref] = (ox + bw - 3 - col * step, y_max + step + row * step, 0)
                occupied.append(_footprint_aabb('passive', layout[ref][0], layout[ref][1], 0, fp_str))
                placed += 1
                print(f"  OVERFLOW: {ref} (anchor {anchor_ref}) — no free slot found")

    print(f"  Placed {placed} right-section passives near anchors")


# ============================================================
# Board-specific layout configurations
# ============================================================

def layout_main():
    """Layout the unified MAIN board (master + ADC + DAC-router + slaves)."""
    board_dir = BOARDS_DIR / "main" / "layout"
    net_path = board_dir / "default.net"

    if not net_path.exists():
        print("  MAIN netlist not found, skipping")
        return

    print("  Parsing netlist...")
    components, nets = parse_netlist(net_path)
    print(f"  Found {len(components)} components, {len(nets)} nets")

    board, fps = create_board("main", components, nets, {'layers': 4})

    # Board dimensions: 100x80mm, 4-layer, three zones
    bw, bh = 100, 80
    ox, oy = 10, 10  # board origin

    layout = {}

    # =================================================================
    # Explicit IC and connector placement by reference designator
    # =================================================================
    #
    # Ref mapping (from netlist analysis, v2.7 — single DevKit footprint):
    #   U1 = ESP32-S3-DevKitC-1 (master, 44-pin Espressif footprint)
    #   J17 = USB-C          J2 = Battery connector
    #   U7 = MCP73831        U6 = LP2985 (AVDD)     U8 = AP2114H (DVDD)
    #   D1 = BAT54           D2 = LED (charge status)
    #   J6/J13 = Slave A     J7/J14 = Slave B
    #   J8/J15 = Slave C     J9/J16 = Slave D
    #   U2 = ES8388 #1 (CH1+2)   U3 = ES8388 #2 (CH3+4)
    #   U4 = ES8388 #3 (CH5+6 + DAC out)   U5 = ES8388 #4 (CH7+8)
    #   J1 = J_AFE (2x5 preamp cable)
    #   U12 = NE5532 summing   U11 = NE5532 output buf
    #   U9 = CD4052B mux #1    U10 = CD4052B mux #2
    #   J5 = HP jack           J10 = Line jack
    #   RV1/RV2 = Volume pots
    #   J11/J12 = Output headers   J3/J4 = Footswitch connectors
    #   FB1 = Ferrite bead (AGND-DGND bridge)

    # ================================================================
    # ZONE A — DIGITAL (left ~70mm, x: ox to ox+70)
    # ================================================================

    # --- Master ESP32-S3-DevKitC-1 (single 44-pin Espressif footprint) ---
    # Rotated 90° CW: USB points right, pins run right-to-left
    # After rotation, pad area is 53.3mm wide x 22.9mm tall
    # Pad1 (origin) ends up at the RIGHT end; leftmost pad is 53.3mm left of pad1
    # Place with leftmost pad at board left edge, centered vertically
    devkit_x = ox + 56.3   # pad1 at right end, leftmost pad at ox+3
    devkit_y = oy + bh / 2 - 11.4  # center pad area at board center Y
    layout['U1'] = (devkit_x, devkit_y, -90)  # ESP32-S3-DevKitC-1, rotated 90° CW

    master_cy = oy + bh / 2    # centered in board Y

    # --- Power supply section (right of DevKit, centered Y) ---
    pwr_row1 = master_cy - 3     # upper row
    pwr_row2 = master_cy + 3     # lower row
    layout['J17'] = (16.025, 45.525, -90)            # USB-C (hand-placed, edge-mount, plug from left)
    layout['U7']  = (ox + 28, pwr_row1, 0)       # MCP73831 charger
    layout['D2']  = (13.7875, 41.5, 0)            # Charge status LED (hand-placed)
    layout['D1']  = (ox + 44, pwr_row1, 0)       # BAT54 reverse protection
    layout['J2']  = (33.5, 55.5, 0)                # Battery connector (hand-placed)
    layout['U8']  = (24, 48.5, 0)                  # AP2114H digital LDO (hand-placed)

    # Ferrite bead at analog/digital zone boundary — placed in moat center (ox+67 = x=77)
    layout['FB1'] = (ox + 67, oy + 32, 0)

    # --- Slave DevKit sockets (2x2 grid, devboards hang over top/bottom edges) ---
    slave_x0 = ox + 4          # first pair LEFT socket X
    slave_y_top = oy + 4       # top row Y (devboards hang over top)
    slave_y_bot = oy + bh - 20 # bottom row Y (devboards hang over bottom)
    slave_pairs = [
        ('J6',  'J13', slave_x0,      slave_y_top),   # Slave A (top-left)
        ('J7',  'J14', slave_x0 + 30, slave_y_top),   # Slave B (top-right)
        ('J8',  'J15', slave_x0,      slave_y_bot),   # Slave C (bottom-left)
        ('J9',  'J16', slave_x0 + 30, slave_y_bot),   # Slave D (bottom-right)
    ]
    for left, right, sx, sy in slave_pairs:
        layout[left]  = (sx, sy, 0)
        layout[right] = (sx + 25.4, sy, 0)

    # ================================================================
    # RIGHT SECTION — ANALOG (x: ox+69 to ox+100, 31mm wide)
    # ================================================================

    # --- Right edge connectors ---
    layout['J5']  = (104.5, 35.5, 90)              # Headphone jack (90° CCW)
    layout['J10'] = (104.5, 49.5, 90)              # Line output jack (90° CCW)
    layout['J11'] = (107, 63, 0)                   # J_OUT_L
    layout['J12'] = (107, 73.92, 0)               # J_OUT_R

    # --- Bottom of right section: AFE preamp cable (2x5) ---
    layout['J1']  = (82.46, 87.5, 90)             # J_AFE preamp cable (hand-placed)

    # --- Top edge: volume pots ---
    # Alps RK09K body extends 14.4mm in X from ref point (-1.15 to +13.25)
    # Need 15mm center-to-center minimum. Board right edge at ox+100=110.
    layout['RV1'] = (ox + 70, oy + 6, 0)         # HP VOL L (courtyard to x=93.25)
    layout['RV2'] = (ox + 85, oy + 6, 0)         # HP VOL R (courtyard to x=108.25)

    # --- Bottom edge: footswitch connectors ---
    layout['J3'] = (98.5, 85, 0)                  # Footswitch 1 (hand-placed)
    layout['J4'] = (102, 85, 0)                   # Footswitch 2 (hand-placed)

    # --- Interior ICs ---
    layout['U2']  = (82,      30.1,    90)         # ES8388 ADC #1 (CH1+2)
    layout['U3']  = (82,      35.9375, 90)         # ES8388 ADC #2 (CH3+4)
    layout['U4']  = (82,      42,      90)         # ES8388 ADC #3 (CH5+6 + DAC)
    layout['U5']  = (82,      47.9375, 90)         # ES8388 ADC #4 (CH7+8)
    # Downstream analog processing
    layout['U6']  = (93,      57,      0)          # LP2985 AVDD analog LDO
    layout['U12'] = (93,      64.4,    0)          # NE5532 summing amp
    layout['U11'] = (93,      74.5,    0)          # NE5532 output buffer

    # Muxes (moved closer to ES8388 column for shorter moat-crossing routes)
    layout['U9']  = (82.975, 58.595, 0)            # CD4052B mux #1
    layout['U10'] = (82.975, 70.595, 0)            # CD4052B mux #2

    # ================================================================
    # Hand-placed passives (override auto-placement)
    # ================================================================
    layout['R8']  = (33.99, 48, 0)               # RPROG for MCP73831 (hand-placed)
    layout['R19'] = (85.49, 81.5, 0)             # Summing resistor (hand-placed)
    layout['R23'] = (88.49, 81.5, 0)             # Summing resistor (hand-placed)

    # ================================================================
    # Passive component clustering (net-based, near parent ICs)
    # ================================================================
    anchor_positions = {ref: (x, y) for ref, (x, y, _) in layout.items()
                        if ref.startswith(('U', 'J', 'FB', 'D'))}

    assignments = assign_passives_to_anchors(fps, nets, anchor_positions)

    # Remove hand-placed passives from auto-assignment
    hand_placed = {r for r in layout if r.startswith(('R', 'C'))}
    for anchor_ref in list(assignments.keys()):
        assignments[anchor_ref] = [r for r in assignments[anchor_ref] if r not in hand_placed]

    print(f"  Passive assignments:")
    for k, v in sorted(assignments.items()):
        print(f"    {k}: {sorted(v)}")

    # Separate right-section passives from left-section passives
    right_section_x = ox + 65  # boundary between left and right sections (moat left edge)
    right_assignments = {}
    left_assignments = {}
    for anchor_ref, passive_list in assignments.items():
        if anchor_ref == 'UNASSIGNED' or anchor_ref not in layout:
            continue
        ax, ay, _ = layout[anchor_ref]
        if ax >= right_section_x:
            right_assignments[anchor_ref] = passive_list
        else:
            left_assignments[anchor_ref] = passive_list

    # Place left-section passives right of DevKit, between it and the moat
    if left_assignments:
        total = sum(len(v) for v in left_assignments.values())
        print(f"  Left-section passives ({total}) across {len(left_assignments)} anchors")
        # DevKit right edge is at ~ox+25; constrain to area right of it to moat
        left_bounds = (ox + 26, ox + 63, master_cy - 11, master_cy + 11)
        place_passives_right_section(left_assignments, layout, ox, oy, bw, bh, fps=fps,
                                     bounds=left_bounds)

    # Place right-section passives near their parent anchors
    if right_assignments:
        total = sum(len(v) for v in right_assignments.values())
        print(f"  Right-section passives ({total}) across {len(right_assignments)} anchors")
        place_passives_right_section(right_assignments, layout, ox, oy, bw, bh, fps=fps, x_min_offset=69)

    # Handle unassigned passives — place in left section available space
    unassigned = assignments.get('UNASSIGNED', [])
    if unassigned:
        print(f"  Unassigned passives: {sorted(unassigned)}")
        for i, ref in enumerate(sorted(unassigned)):
            col = i % 8
            row = i // 8
            layout[ref] = (ox + 70 + col * 4, oy + 30 + row * 3, 0)

    # Any remaining unplaced components
    remaining = [r for r in fps if r not in layout]
    if remaining:
        print(f"  Remaining unplaced: {remaining}")
        for i, ref in enumerate(remaining):
            layout[ref] = (ox + 5 + (i % 10) * 7, oy + bh - 10 + (i // 10) * 4, 0)

    place_components_grid(board, fps, layout)
    add_board_outline(board, ox, oy, bw, bh, corner_radius=2)
    add_silkscreen_labels(board, components, fps, layout)

    # Ground copper pours — mixed-signal moat topology
    #
    # Moat (no copper) at x = [ox+65, ox+69] = [75, 79] — 4mm gap on all layers
    # FB1 bridges DGND↔AGND at x=77 (moat center)
    # Digital traces must NOT cross the moat; only FB1 and the ADC I2S/SPI signals
    # cross the boundary (at the ADC pads themselves, never in open routing).
    #
    # DGND: left (digital) section only — F.Cu, B.Cu, and In1.Cu
    MOAT_LEFT = 65   # mm from ox — moat left edge
    MOAT_RIGHT = 69  # mm from ox — moat right edge (4mm moat)
    add_ground_pour(board, "DGND", "F.Cu",  ox,            oy, MOAT_LEFT,          bh)
    add_ground_pour(board, "DGND", "B.Cu",  ox,            oy, MOAT_LEFT,          bh)
    add_ground_pour(board, "DGND", "In1.Cu", ox,           oy, MOAT_LEFT,          bh)
    # DGND corridor on In1.Cu extending through moat into analog zone.
    # Provides digital return current path for I2S and data traces on In1.Cu
    # to ES8388 codecs (U2-U5 at x=82, y=30..48) and CD4052B muxes.
    # Extended north to y=25 to cover clock fan-out trunks at y=26-27.
    # I2C now routed on In2.Cu (separate from I2S) but corridor still needed
    # for I2S clocks, data, and MUX control signals.
    CORRIDOR_X = ox + MOAT_LEFT  # starts at moat left edge (x=75)
    CORRIDOR_W = 14              # extends to x=89, past ES8388 DGND pads and MUX via columns
    CORRIDOR_Y = 25              # above clock fan-out trunks (MCLK trunk at y=26)
    CORRIDOR_H = 52              # down to y=77, below U10 mux (y=70.6) MUX_B pad at y=75
    add_ground_pour(board, "DGND", "In1.Cu", CORRIDOR_X, CORRIDOR_Y, CORRIDOR_W, CORRIDOR_H)
    # AGND: right (analog) section — F.Cu, B.Cu, and In2.Cu
    add_ground_pour(board, "AGND", "F.Cu",  ox + MOAT_RIGHT, oy, bw - MOAT_RIGHT,  bh)
    add_ground_pour(board, "AGND", "B.Cu",  ox + MOAT_RIGHT, oy, bw - MOAT_RIGHT,  bh)
    add_ground_pour(board, "AGND", "In2.Cu", ox + MOAT_RIGHT, oy, bw - MOAT_RIGHT, bh)

    out_path = str(board_dir / "layout.kicad_pcb")
    pcbnew.SaveBoard(out_path, board)
    hide_fab_layers(str(board_dir / "layout.kicad_pro"))
    print(f"  Saved: {out_path}")


def layout_preamp():
    """Layout the 8-channel preamp/AFE board."""
    board_dir = BOARDS_DIR / "preamp" / "layout"
    net_path = board_dir / "default.net"

    if not net_path.exists():
        print("  Preamp netlist not found, skipping")
        return

    print("  Parsing netlist...")
    components, nets = parse_netlist(net_path)
    print(f"  Found {len(components)} components, {len(nets)} nets")

    board, fps = create_board("preamp", components, nets, {'layers': 4})

    # Match main board dimensions: 100x80mm
    bw, bh = 100, 80
    ox, oy = 10, 10

    layout = {}

    # Build ref -> zen_name map from parsed components
    ref_to_zen = {comp['ref']: comp.get('zen_name', '') for comp in components}

    # ================================================================
    # J17 (output to main board) — match main board's J3 (J_AFE) position
    # Main board: J3 at (79.46, 87.54, 90)
    # ================================================================
    layout['J17'] = (79.46, 87.54, 90)

    # ================================================================
    # Pickup input pads (J9-J16) — along bottom-left edge, 2.54mm pitch
    # Rotation=90 places pins horizontally: pin1 (signal) left, pin2 (GND) right.
    # 8 headers at 5.08mm X spacing form a contiguous 1x16 array at 2.54mm pitch.
    # ================================================================
    input_refs = sorted([r for r in fps if ref_to_zen.get(r, '').startswith('J_IN')])
    for i, ref in enumerate(input_refs):
        layout[ref] = (ox + 5 + i * 5.08, oy + bh - 3.8, 90)

    # ================================================================
    # Direct output pads (J1-J8) — along left edge, 2.54mm pitch
    # Rotation=0 places pins horizontally: col 0 = signals, col 1 = GND.
    # 8 headers at 2.54mm Y spacing form a 2x8 grid compatible with
    # a single 2x8 2.54mm pitch connector.
    # ================================================================
    dout_refs = sorted([r for r in fps if ref_to_zen.get(r, '').startswith('J_DOUT')])
    for i, ref in enumerate(dout_refs):
        layout[ref] = (ox + 3.8, oy + 15 + i * 5.08, 0)

    # ================================================================
    # Power input J18 — user-placed position (preserved from KiCad)
    # ================================================================
    for ref in fps:
        if ref_to_zen.get(ref, '') == 'J_PWR':
            layout[ref] = (94.96, 87.00, 90)

    # ================================================================
    # ICs — evenly spaced grid
    # Signal flow: buffer (U5-U8) -> gain (U9-U12) -> filter (U1-U4)
    # U13 = VGND reference, placed near power
    # U14 = local LP2985 AVDD LDO — user-placed position (preserved from KiCad)
    # ================================================================
    ic_rows = [
        ['U5', 'U6', 'U7', 'U8'],       # Input buffers
        ['U9', 'U10', 'U11', 'U12'],     # Gain stages
        ['U1', 'U2', 'U3', 'U4'],        # Anti-alias filters
    ]
    x_positions = [40, 55, 70, 85]   # 15mm spacing, shifted right
    y_positions = [20, 35, 50]       # 15mm spacing vertically

    for row_idx, row_refs in enumerate(ic_rows):
        for col_idx, ref in enumerate(row_refs):
            if ref in fps:
                layout[ref] = (x_positions[col_idx], y_positions[row_idx], 0)

    # U13 (VGND) near power/output connector
    if 'U13' in fps:
        layout['U13'] = (55, 62, 0)

    # U14 (local LP2985 AVDD LDO) — user-placed, near J18 (J_PWR)
    if 'U14' in fps:
        layout['U14'] = (90.53, 76.41, 0)

    # ================================================================
    # Trimpots (RV1-RV8) — right edge column
    # ================================================================
    trim_refs = sorted([r for r in fps if r.startswith('RV')])
    for i, ref in enumerate(trim_refs):
        layout[ref] = (ox + bw - 6, oy + 6 + i * 9, 0)

    # ================================================================
    # Passive placement — same AABB strategy as main board right side
    # ================================================================
    anchor_positions = {ref: (x, y) for ref, (x, y, _) in layout.items()
                        if ref.startswith(('U', 'J', 'RV'))}

    assignments = assign_passives_to_anchors(fps, nets, anchor_positions)

    print(f"  Passive assignments:")
    for k, v in sorted(assignments.items()):
        print(f"    {k}: {sorted(v)}")

    # Place all passives using AABB collision strategy across full board
    all_assignments = {}
    for anchor_ref, passive_list in assignments.items():
        if anchor_ref == 'UNASSIGNED' or anchor_ref not in layout:
            continue
        all_assignments[anchor_ref] = passive_list

    if all_assignments:
        total = sum(len(v) for v in all_assignments.values())
        print(f"  Passives ({total}) across {len(all_assignments)} anchors")
        place_passives_right_section(all_assignments, layout, ox, oy, bw, bh,
                                     fps=fps, x_min_offset=3)

    # Handle unassigned passives
    unassigned = assignments.get('UNASSIGNED', [])
    if unassigned:
        print(f"  Unassigned passives: {sorted(unassigned)}")
        for i, ref in enumerate(sorted(unassigned)):
            col = i % 8
            row = i // 8
            layout[ref] = (ox + 20 + col * 4, oy + 65 + row * 3, 0)

    # Remaining unplaced
    remaining = [r for r in fps if r not in layout]
    if remaining:
        print(f"  Remaining unplaced: {remaining}")
        for i, ref in enumerate(remaining):
            layout[ref] = (ox + 5 + (i % 10) * 7, oy + bh - 10 + (i // 10) * 4, 0)

    place_components_grid(board, fps, layout)
    add_board_outline(board, ox, oy, bw, bh, corner_radius=2)
    add_silkscreen_labels(board, components, fps, layout)
    add_ground_pour(board, "GND", "F.Cu", ox, oy, bw, bh)
    add_ground_pour(board, "GND", "B.Cu", ox, oy, bw, bh)

    out_path = str(board_dir / "layout.kicad_pcb")
    pcbnew.SaveBoard(out_path, board)
    hide_fab_layers(str(board_dir / "layout.kicad_pro"))
    print(f"  Saved: {out_path}")



def main():
    print("=" * 60)
    print("Auto-Layout for Preamp-Zener PCB Boards")
    print("=" * 60)

    boards = [
        ("MAIN", layout_main),
        ("Preamp", layout_preamp),
    ]

    for name, layout_fn in boards:
        print(f"\n--- {name} Board ---")
        try:
            layout_fn()
        except Exception as e:
            print(f"  ERROR: {e}")
            import traceback
            traceback.print_exc()

    # Route moat-crossing digital traces on MAIN board
    print("\n--- MAIN Board: Moat Routing ---")
    try:
        from route_moat import main as route_moat_main
        route_moat_main()
    except Exception as e:
        print(f"  ERROR: {e}")
        import traceback
        traceback.print_exc()

    print("\n" + "=" * 60)
    print("Auto-layout complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
