[board]
name = "dac_router"
path = "dac_router.zen"

[dependencies]
"github.com/deepinthewoods/octo-preamp/components/audio_pot" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/cd4052b" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/ht8988a" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/ne5532" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/stereo_jack" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/modules/decoupling" = "0.1.0"
