[board]
name = "main"
path = "main.zen"

[dependencies]
"github.com/deepinthewoods/octo-preamp/components/ap2114h" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/audio_pot" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/bat54" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/cd4052b" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/es8388" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/esp32_s3" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/esp32_s3_devkit" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/ht8988a" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/lp2985" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/mcp73831" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/ne5532" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/stereo_jack" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/components/usb_c" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/modules/decoupling" = "0.1.0"
"github.com/deepinthewoods/octo-preamp/modules/i2c_bus" = "0.1.0"
